[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=UTF-8"
    Cache-Control = "no-cache"